spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/king_yurina}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mariadb.sql
      data-locations:
        - classpath:data-mariadb.sql
        - classpath:data-etf-seed.sql

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
